table 'Gender Table'
	lineageTag: 18259435-d51d-4768-b73d-cd40ca424762

	column 'Gender ID'
		dataType: int64
		formatString: 0
		lineageTag: 3c52456f-7623-47aa-b588-668af154dbf9
		summarizeBy: none
		sourceColumn: Gender ID

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: f6597814-4d23-4bfd-b173-6b67c5191516
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	partition 'Gender Table' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Projects\Power BI\Project-1\Customers_C.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Cust_Id", Int64.Type}, {"First_Name", type text}, {"Last_Name", type text}, {"Gender", type text}, {"Age", Int64.Type}, {"Location", type text}, {"Occupation", type text}, {"Annual_Income", type number}, {"Marital_Status", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [Cust_Id] <> null and [Cust_Id] <> ""),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Gender"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Other Columns", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Gender"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "Gender ID"}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Renamed Columns", each [Gender] <> null and [Gender] <> ""),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows1", {"Gender"}),
				    #"Added Index1" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Index1",{"Gender ID"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns",{"Index", "Gender"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns1",{{"Index", "Gender ID"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

