table 'Location Table'
	lineageTag: 6ed6d93b-bb22-48d6-ac10-b9c24d72932d

	column 'Location ID'
		dataType: int64
		formatString: 0
		lineageTag: de041601-6af1-4940-bd9a-acb625d286ad
		summarizeBy: count
		sourceColumn: Location ID

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 60314a4b-363a-470e-a1bd-a234d85e38ba
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	partition 'Location Table' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Projects\Power BI\Project-1\Customers_C.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Cust_Id", Int64.Type}, {"First_Name", type text}, {"Last_Name", type text}, {"Gender", type text}, {"Age", Int64.Type}, {"Location", type text}, {"Occupation", type text}, {"Annual_Income", type number}, {"Marital_Status", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [Cust_Id] <> null and [Cust_Id] <> ""),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Location"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Other Columns", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Location"}),
				    #"Removed Duplicates" = Table.Distinct(#"Reordered Columns", {"Location"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Duplicates",{"Index"}),
				    #"Added Index1" = Table.AddIndexColumn(#"Removed Columns", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Index1",{"Index", "Location"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns1",{{"Index", "Location ID"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

