table 'Occupation Table'
	lineageTag: 6eae9728-6c97-4f87-98c9-035bcef9e373

	column 'Occupation ID'
		dataType: int64
		formatString: 0
		lineageTag: 4a16d434-c173-4256-ad5e-abc91c750796
		summarizeBy: none
		sourceColumn: Occupation ID

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: 3d933e23-72a0-4cca-95e7-396053d15870
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	partition 'Occupation Table' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Projects\Power BI\Project-1\Customers_C.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Cust_Id", Int64.Type}, {"First_Name", type text}, {"Last_Name", type text}, {"Gender", type text}, {"Age", Int64.Type}, {"Location", type text}, {"Occupation", type text}, {"Annual_Income", type number}, {"Marital_Status", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [Cust_Id] <> null and [Cust_Id] <> ""),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Occupation"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Occupation"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "Occupation ID"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

